### PR TITLE
Hackathon

### PR DESCRIPTION
**Pull request by derTobsch**

### CODE REVIEW

**Comment by derTobsch** [comment]
hey @Jeija, we wanted to let you know that we hacked a little bit of your great work at a hackathon at synyx (https://github.com/synyx/). It was late and I thought I did a merge request to our fork :D But as you an see I made a merge request to your repository. I would close this merge request, but now you now that we did something and you can take a look. If we find the time, we would create some clean merge request for each feature we created or fixes and so on :)

**Comment by Jeija** [comment]
Hey @derTobsch!
Sooo much new code 😯! I've been following your progress the past hours / days.
I see that you must have been putting quite a lot of work into this, thanks!
I hope you understand that I won't be able to review and merge all of this code straight away, so please have some patience with me... As I've seen, you have already started opening PRs for some isolated features, I will try to review and hopefully merge these a bit earlier...

**Comment by derTobsch** [comment]
Hey @Jeija, nice to hear from you. Yes I think it will be better if we open PRs for each usecase/new stuff, so it will be more easy to see what is going on :)

**Comment by derTobsch** [comment]
Hey @Jeija how does it look? Are these PRs are ok? :)

**Pull request closed without merging**
